# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5fcadfb3d406080d11a5ac1862fa5dd188ce87ba6c6ac4c929dfc9d18dae5aed3d4ed09537181820b8e4077bb240d60b45750ffd68ec7df8e4980b5eca3c6408

test:
  secret_key_base: 6e72fda8d07938230102d70d789ae023a81f9a1aefae1e593a7638ff43a65bb4a38fa2c7c08865369d7697a530f1df0486b5c239a28c224dd7e155feb7f390d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
